version: '3.9'
services:
  gateway:
    image: gateway:latest
    environment:
      - PORT=12345
      - BACKEND_URL=http://backend:12345
    volumes:
      - ./app:/code/app
    ports:
      - "12346:12345"
    restart: on-failure
    networks:
      - eventito-dev-network

networks:
  eventito-dev-network:
    name: eventito-dev-network
    external: true
